--- #YAML:1.0
name:                Sane
version:             0.02
abstract:            Perl extension for the SANE (Scanner Access Now Easy) Project
license:             ~
author:              
    - Jeffrey Ratcliffe
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
